// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NonStop.SitUpStraight.Bot.Db;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NonStop.SitUpStraight.Bot.Migrations
{
    [DbContext(typeof(SitUpStraightDbContext))]
    [Migration("20260822202113_AddStatsAndFeedback")]
    partial class AddStatsAndFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NonStop.SitUpStraight.Bot.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImproveOption")
                        .HasColumnType("text");

                    b.Property<string>("LikedOption")
                        .HasColumnType("text");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("NonStop.SitUpStraight.Bot.Models.Subscriber", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatId"));

                    b.Property<bool>("Configured")
                        .HasColumnType("boolean");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("EndHourUtc")
                        .HasColumnType("integer");

                    b.Property<int>("LegendaryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Offset")
                        .HasColumnType("integer");

                    b.Property<int>("StartHourUtc")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMessagesSent")
                        .HasColumnType("integer");

                    b.HasKey("ChatId");

                    b.ToTable("Subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
